-- Clínica da Alma — schema Supabase definitivo
-- Execute este arquivo no SQL Editor do Supabase ou via Supabase CLI.
-- Ele cria a base persistente para clientes, espaços terapêuticos, sessões,
-- prontuários, histórico emocional/energético, observações, protocolos,
-- meditações, uploads e registros financeiros.

create extension if not exists pgcrypto;

-- Tipos de domínio
create type if not exists public.user_role as enum ('user', 'admin');
create type if not exists public.session_type as enum ('individual', 'group', 'online');
create type if not exists public.appointment_status as enum ('scheduled', 'completed', 'cancelled', 'no-show');
create type if not exists public.audio_type as enum ('meditation', 'session_recording', 'personal_note', 'protocol_audio', 'other');
create type if not exists public.protocol_status as enum ('active', 'paused', 'completed', 'archived');
create type if not exists public.meditation_difficulty as enum ('beginner', 'intermediate', 'advanced');
create type if not exists public.financial_record_type as enum ('income', 'expense');
create type if not exists public.upload_kind as enum ('document', 'image', 'audio', 'video', 'report', 'contract', 'other');

-- Atualização automática de updated_at
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Usuários/terapeutas do sistema. Mantém compatibilidade com o app atual,
-- mas sem dependência de Manus Auth.
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  open_id text not null unique,
  name text,
  email text unique,
  login_method text default 'local' not null,
  password_hash text,
  role public.user_role default 'admin' not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  last_signed_in timestamptz default now() not null
);

create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

-- Áreas/espaços terapêuticos: salas, espaços online, unidades ou linhas de atendimento.
create table if not exists public.therapeutic_spaces (
  id bigint generated by default as identity primary key,
  therapist_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  space_type text,
  description text,
  address text,
  city text,
  state text,
  online_url text,
  is_active boolean default true not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create trigger therapeutic_spaces_set_updated_at
before update on public.therapeutic_spaces
for each row execute function public.set_updated_at();

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  therapist_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  date_of_birth date,
  address text,
  city text,
  state text,
  zip_code text,
  emergency_contact text,
  emergency_phone text,
  notes text,
  is_active boolean default true not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists clients_therapist_id_idx on public.clients(therapist_id);
create index if not exists clients_name_idx on public.clients using gin (to_tsvector('portuguese', coalesce(name, '')));

create trigger clients_set_updated_at
before update on public.clients
for each row execute function public.set_updated_at();

create table if not exists public.therapeutic_records (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  therapist_id bigint not null references public.users(id) on delete cascade,
  main_complaint text,
  medical_history text,
  emotional_blockages text,
  personal_goals text,
  notes text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  unique(client_id)
);

create trigger therapeutic_records_set_updated_at
before update on public.therapeutic_records
for each row execute function public.set_updated_at();

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  therapist_id bigint not null references public.users(id) on delete cascade,
  therapeutic_space_id bigint references public.therapeutic_spaces(id) on delete set null,
  session_date timestamptz not null,
  duration integer,
  session_notes text,
  emotional_state text,
  energetic_state text,
  techniques text,
  session_type public.session_type default 'individual',
  price numeric(10,2),
  paid boolean default false,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists sessions_client_id_idx on public.sessions(client_id);
create index if not exists sessions_therapist_id_idx on public.sessions(therapist_id);
create index if not exists sessions_session_date_idx on public.sessions(session_date);

create trigger sessions_set_updated_at
before update on public.sessions
for each row execute function public.set_updated_at();

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  therapist_id bigint not null references public.users(id) on delete cascade,
  therapeutic_space_id bigint references public.therapeutic_spaces(id) on delete set null,
  appointment_date timestamptz not null,
  duration integer default 60,
  status public.appointment_status default 'scheduled',
  notes text,
  reminder_sent boolean default false,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists appointments_therapist_date_idx on public.appointments(therapist_id, appointment_date);

create trigger appointments_set_updated_at
before update on public.appointments
for each row execute function public.set_updated_at();

-- Histórico emocional e energético longitudinal.
create table if not exists public.emotional_evolution (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  therapist_id bigint not null references public.users(id) on delete cascade,
  record_date date not null,
  emotional_state integer check (emotional_state between 1 and 10),
  anxiety integer check (anxiety between 1 and 10),
  depression integer check (depression between 1 and 10),
  wellbeing integer check (wellbeing between 1 and 10),
  energetic_state integer check (energetic_state between 1 and 10),
  energy_notes text,
  notes text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists emotional_evolution_client_date_idx on public.emotional_evolution(client_id, record_date);

create trigger emotional_evolution_set_updated_at
before update on public.emotional_evolution
for each row execute function public.set_updated_at();

-- Observações livres da terapeuta, separadas do prontuário principal.
create table if not exists public.therapist_observations (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  therapist_id bigint not null references public.users(id) on delete cascade,
  session_id bigint references public.sessions(id) on delete set null,
  title text,
  observation text not null,
  is_private boolean default true not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists therapist_observations_client_idx on public.therapist_observations(client_id);

create trigger therapist_observations_set_updated_at
before update on public.therapist_observations
for each row execute function public.set_updated_at();

create table if not exists public.protocols (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  therapist_id bigint not null references public.users(id) on delete cascade,
  protocol_name text not null,
  description text,
  steps text,
  frequency text,
  duration text,
  status public.protocol_status default 'active' not null,
  is_active boolean default true,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create trigger protocols_set_updated_at
before update on public.protocols
for each row execute function public.set_updated_at();

create table if not exists public.meditations (
  id bigint generated by default as identity primary key,
  therapist_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  description text,
  audio_url text,
  audio_key text,
  duration integer,
  category text,
  difficulty public.meditation_difficulty default 'beginner',
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create trigger meditations_set_updated_at
before update on public.meditations
for each row execute function public.set_updated_at();

create table if not exists public.audio_files (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  therapist_id bigint not null references public.users(id) on delete cascade,
  session_id bigint references public.sessions(id) on delete set null,
  protocol_id bigint references public.protocols(id) on delete set null,
  title text not null,
  description text,
  audio_url text not null,
  audio_key text not null,
  duration integer,
  file_type text,
  file_size bigint,
  audio_type public.audio_type default 'other',
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists audio_files_client_idx on public.audio_files(client_id);
create index if not exists audio_files_therapist_idx on public.audio_files(therapist_id);

create trigger audio_files_set_updated_at
before update on public.audio_files
for each row execute function public.set_updated_at();

create table if not exists public.client_meditations (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  meditation_id bigint not null references public.meditations(id) on delete cascade,
  recommended_date timestamptz default now(),
  completed boolean default false,
  completed_date timestamptz,
  notes text,
  created_at timestamptz default now() not null
);

create table if not exists public.treatment_evolution (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  therapist_id bigint not null references public.users(id) on delete cascade,
  session_id bigint references public.sessions(id) on delete set null,
  record_date date default current_date not null,
  progress_summary text,
  therapeutic_focus text,
  next_steps text,
  perceived_progress integer check (perceived_progress between 1 and 10),
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists treatment_evolution_client_date_idx on public.treatment_evolution(client_id, record_date);

create trigger treatment_evolution_set_updated_at
before update on public.treatment_evolution
for each row execute function public.set_updated_at();

create table if not exists public.uploads (
  id bigint generated by default as identity primary key,
  therapist_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  session_id bigint references public.sessions(id) on delete set null,
  therapeutic_record_id bigint references public.therapeutic_records(id) on delete set null,
  title text,
  file_name text not null,
  file_path text not null,
  file_url text,
  mime_type text,
  file_size bigint,
  kind public.upload_kind default 'other' not null,
  created_at timestamptz default now() not null
);

create index if not exists uploads_therapist_idx on public.uploads(therapist_id);
create index if not exists uploads_client_idx on public.uploads(client_id);

create table if not exists public.financial_records (
  id bigint generated by default as identity primary key,
  therapist_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  session_id bigint references public.sessions(id) on delete set null,
  amount numeric(10,2) not null,
  description text,
  record_type public.financial_record_type default 'income',
  payment_method text,
  record_date date not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists financial_records_therapist_date_idx on public.financial_records(therapist_id, record_date);

create trigger financial_records_set_updated_at
before update on public.financial_records
for each row execute function public.set_updated_at();

-- Storage Supabase: bucket privado para documentos, áudios e prontuários.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'clinica-da-alma-files',
  'clinica-da-alma-files',
  false,
  104857600,
  array[
    'application/pdf', 'image/jpeg', 'image/png', 'image/webp',
    'audio/mpeg', 'audio/mp3', 'audio/wav', 'audio/webm', 'audio/mp4',
    'video/mp4', 'text/plain',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- RLS: a API do sistema usa service_role no backend, portanto bloqueamos acesso anônimo direto.
alter table public.users enable row level security;
alter table public.therapeutic_spaces enable row level security;
alter table public.clients enable row level security;
alter table public.therapeutic_records enable row level security;
alter table public.sessions enable row level security;
alter table public.appointments enable row level security;
alter table public.emotional_evolution enable row level security;
alter table public.therapist_observations enable row level security;
alter table public.protocols enable row level security;
alter table public.meditations enable row level security;
alter table public.audio_files enable row level security;
alter table public.client_meditations enable row level security;
alter table public.treatment_evolution enable row level security;
alter table public.uploads enable row level security;
alter table public.financial_records enable row level security;

-- Políticas de negação explícita para anon/authenticated direto. O backend com service_role ignora RLS.
do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'users','therapeutic_spaces','clients','therapeutic_records','sessions','appointments',
    'emotional_evolution','therapist_observations','protocols','meditations','audio_files',
    'client_meditations','treatment_evolution','uploads','financial_records'
  ] loop
    execute format('drop policy if exists "deny_direct_client_access" on public.%I', tbl);
    execute format('create policy "deny_direct_client_access" on public.%I for all to anon, authenticated using (false) with check (false)', tbl);
  end loop;
end $$;

drop policy if exists "deny_direct_storage_access" on storage.objects;
create policy "deny_direct_storage_access"
on storage.objects for all to anon, authenticated
using (bucket_id <> 'clinica-da-alma-files')
with check (bucket_id <> 'clinica-da-alma-files');

-- Usuário inicial opcional. Ajuste os dados após a primeira implantação se desejar.
insert into public.users (open_id, name, email, login_method, role)
values ('clinica-da-alma-local-owner', 'Clínica da Alma', null, 'local', 'admin')
on conflict (open_id) do update set
  name = excluded.name,
  login_method = excluded.login_method,
  role = excluded.role,
  updated_at = now();
